## Config for RandomTrivia 1.0, made by Benjozork

questions: # List of questions.
    - 'What year is it ?'

answers: # List of answers, must be in the same order as the questions.
    - '2016'

command: 'give %PLAYER% apple 27' # The command to execute when a player wins a question.

messages: # All the plugin messages.
    plugin_info: 'by &eBenjozork'
    global_prefix: '&b[Trivia]&r '
    question_starting: '&aQuestion starting!'
    question_is: '&aThe question is: &b'
    no_question: '&cNo question is active right now.'
    answer_correct: '&aCorrect!'
    answer_incorrect: '&cIncorrect! Better luck next time!'
    winner_is: '&aThe winner is: &b'
    no_winner: '&cNo winner in allowed time.'
    answer_was: '&aThe answer was: &b'

interval: 10 # in seconds
minimum_players: 0 # minimum players needed for questions to be broadcasted.