## Config for Trivia 1.1, made by Benjozork.

command: 'give %PLAYER% apple 27' # The command to execute when a player wins a question.

messages: # All the plugin messages.
    plugin_info: '&aTrivia version 1.1 by &bBenjozork'
    global_prefix: '&b[Trivia]&r '
    permission:
        no_permission_answer: '&cYou have no pemrission to answer the questions!'
        no_permission_top: '&cYou have no pemrission to view the leaderboard!'
        no_permission_reload: '&cYou have no pemrission to relaod the configs!'
    question_starting: '&aQuestion starting!'
    question_is: '&aThe question is: &b'
    no_question: '&cNo question is active right now.'
    answer_correct: '&aCorrect!'
    answer_incorrect: '&cIncorrect! Better luck next time!'
    winner_is: '&aThe winner is: &b'
    no_winner: '&cNo winner in allowed time.'
    answer_was: '&aThe answer was: &b'
    answers_were: '&aThe possible answers were: &b'
    reload_complete: '&aReload complete.'
    top_players_header: '&aTop Trivia winners:'

delay: 60 # Time given to asnwer a question.
minimum_players: 0 # Minimum players needed for questions to be broadcasted.
max_leaderboard_entries: 10 # How many leaderboard entries are shown.
give_answer: false # If the answer(s) are broadcasted when a question is won.
give_all_answers: false # If all the possible answers are broadcasted.