name: Trivia
author: Benjozork
version: '1.2'
main: me.benjozork.trivia.Trivia
softdepend: [PlaceholderAPI]
commands:
    trivia:
        description: Answer the trivia question.
        aliases: [tr]
permissions:
    trivia.answer:
        description: Allows the player to answer the Trivia question.
    trivia.top:
        description: Allows the player to view the top Trivia players.
    trivia.reload:
        description: Allows the player to reload the Trivia config and data files.
    trivia.toggle:
        description: Allows the player to toggle the broadcasting of Trivia questions.